document.write('<section class="section-9 wow fadeInDown">');
document.write('    <div class="container">');
document.write('        <div class="row justify-content-center">');
document.write('            <div class="col-lg-8 text-center">');
document.write('                <h2>Register for our ‍Free <br> 7-Day Trial now!</h2>');
document.write('                <div class="d-flex gap-4 justify-content-center mt-4 flex-sm-row flex-column align-items-center">');
document.write('                    <div class="d-flex gap-2 align-items-center">');
document.write('                        <img src="./frontend/img/home-page/Tick.svg" alt="">');
document.write('                        <p class="mb-0">No credit card required</p>');
document.write('                    </div>');
document.write('                    <div class="d-flex gap-2 align-items-center">');
document.write('                        <img src="./frontend/img/home-page/Tick.svg" alt="">');
document.write('                        <p class="mb-0">Cancel anytime</p>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('            <div class="col-lg-10">');
document.write('                <form action="">');
document.write('                    <div class="input-wrap mt-5">');
document.write('                        <input type="email" name="email" id="email" placeholder="Enter your email address">');
document.write('                        <a href="javascript:void(0)" class="theme_btn_dark">Subscribe Now</a>');
document.write('                    </div>');
document.write('                </form>');
document.write('            </div>');
document.write('        </div>');
document.write('    </div>');
document.write('</section>');
