document.write('<footer class="footer">');
document.write('    <div class="container">');
document.write('        <div class="cols-wrap">');
document.write('            <div class="f-col">');
document.write('                <h3>product</h3>');
document.write('                <ul>');
document.write('                    <li><a href="">Insights</a></li>');
document.write('                    <li><a href="">Risk Processing</a></li>');
document.write('                    <li><a href="">PCI Compliance</a></li>');
document.write('                    <li><a href="">Integrations</a></li>');
document.write('                    <li><a href="">Pricing</a></li>');
document.write('                </ul>');
document.write('            </div>');
document.write('            <div class="f-col">');
document.write('                <h3>for developers</h3>');
document.write('                <ul>');
document.write('                    <li><a href="">Docs</a></li>');
document.write('                    <li><a href="">Knowledge base</a></li>');
document.write('                    <li><a href="">System status</a></li>');
document.write('                    <li><a href="">Tutorials</a></li>');
document.write('                    <li><a href="">Blog</a></li>');
document.write('                </ul>');
document.write('            </div>');
document.write('            <div class="f-col">');
document.write('                <h3>for brands</h3>');
document.write('                <ul>');
document.write('                    <li><a href="">Brands</a></li>');
document.write('                    <li><a href="">Performance Marketing</a></li>');
document.write('                    <li><a href="">Publishers</a></li>');
document.write('                    <li><a href="">Styleguide</a></li>');
document.write('                </ul>');
document.write('            </div>');
document.write('            <div class="f-col">');
document.write('                <h3>resources</h3>');
document.write('                <ul>');
document.write('                    <li><a href="">Case Studies</a></li>');
document.write('                    <li><a href="">Events</a></li>');
document.write('                    <li><a href="">Blog</a></li>');
document.write('                    <li><a href="">Portfoloi</a></li>');
document.write('                </ul>');
document.write('            </div>');
document.write('            <div class="f-col">');
document.write('                <h3>About</h3>');
document.write('                <ul>');
document.write('                    <li><a href="">About us</a></li>');
document.write('                    <li><a href="">Leadership</a></li>');
document.write('                    <li><a href="">Press/News</a></li>');
document.write('                    <li><a href="">Careers/Team</a></li>');
document.write('                    <li><a href="">Contact Us</a></li>');
document.write('                </ul>');
document.write('            </div>');
document.write('        </div>');
document.write('        <div class="copyright">');
document.write('            <div class="row">');
document.write('                <div class="col-lg-4">');
document.write('                    <div class="d-flex gap-4 justify-content-lg-start justify-content-center mb-lg-0 mb-3">');
document.write('                        <li><a href="">Terms</a></li>');
document.write('                        <li><a href="">Privacy</a></li>');
document.write('                        <li><a href="">Security</a></li>');
document.write('                    </div>');
document.write('                </div>');
document.write('                <div class="col-lg-4 text-center">');
document.write('                    <p>© 2023 Gro.Pro | All Rights Reserved</p>');
document.write('                </div>');
document.write('                <div class="col-lg-4">');
document.write('                    <div class="d-flex gap-4 justify-content-lg-start justify-content-center mb-lg-0 mb-3">');
document.write('                        <a href="#"><img src="./frontend/img/socail-media/twitter.svg" alt=""></a>');
document.write('                        <a href=""><img src="./frontend/img/socail-media/Instagram.svg" alt=""></a>');
document.write('                        <a href="#"><img src="./frontend/img/socail-media/facebook.svg" alt=""></a>');
document.write('                        <a href="#"><img src="./frontend/img/socail-media/linkedin.svg" alt=""></a>');
document.write('                        <a href="#"><img src="./frontend/img/socail-media/Instagram.svg" alt=""></a>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('        </div>');
document.write('    </div>');
document.write('</footer>');