document.write('<footer class="footer">');
document.write('    <div class="container">');
document.write('        <div class="cols-wrap">');
document.write('            <div class="f-col">');
document.write('                <h3>product</h3>');
document.write('                <ul>');
document.write('                    <li><a href="javascript:void(0)">Insights</a></li>');
document.write('                    <li><a href="javascript:void(0)">Risk Processing</a></li>');
document.write('                    <li><a href="javascript:void(0)">PCI Compliance</a></li>');
document.write('                    <li><a href="javascript:void(0)">Integrations</a></li>');
document.write('                    <li><a href="javascript:void(0)">Pricing</a></li>');
document.write('                </ul>');
document.write('            </div>');
document.write('            <div class="f-col">');
document.write('                <h3>for developers</h3>');
document.write('                <ul>');
document.write('                    <li><a href="javascript:void(0)">Docs</a></li>');
document.write('                    <li><a href="javascript:void(0)">Knowledge base</a></li>');
document.write('                    <li><a href="javascript:void(0)">System status</a></li>');
document.write('                    <li><a href="javascript:void(0)">Tutorials</a></li>');
document.write('                    <li><a href="javascript:void(0)">Blog</a></li>');
document.write('                </ul>');
document.write('            </div>');
document.write('            <div class="f-col">');
document.write('                <h3>for brands</h3>');
document.write('                <ul>');
document.write('                    <li><a href="javascript:void(0)">Brands</a></li>');
document.write('                    <li><a href="javascript:void(0)">Performance Marketing</a></li>');
document.write('                    <li><a href="javascript:void(0)">Publishers</a></li>');
document.write('                    <li><a href="javascript:void(0)">Styleguide</a></li>');
document.write('                </ul>');
document.write('            </div>');
document.write('            <div class="f-col">');
document.write('                <h3>resources</h3>');
document.write('                <ul>');
document.write('                    <li><a href="javascript:void(0)">Case Studies</a></li>');
document.write('                    <li><a href="javascript:void(0)">Events</a></li>');
document.write('                    <li><a href="javascript:void(0)">Blog</a></li>');
document.write('                    <li><a href="javascript:void(0)">Portfoloi</a></li>');
document.write('                </ul>');
document.write('            </div>');
document.write('            <div class="f-col">');
document.write('                <h3>About</h3>');
document.write('                <ul>');
document.write('                    <li><a href="./about.html">About us</a></li>');
document.write('                    <li><a href="javascript:void(0)">Leadership</a></li>');
document.write('                    <li><a href="javascript:void(0)">Press/News</a></li>');
document.write('                    <li><a href="./career.html">Careers/Team</a></li>');
document.write('                    <li><a href="./contact-us.html">Contact Us</a></li>');
document.write('                </ul>');
document.write('            </div>');
document.write('        </div>');
document.write('        <div class="copyright">');
document.write('            <div class="row align-items-center">');
document.write('                <div class="col-lg-4">');
document.write('                    <div class="d-flex gap-4 justify-content-lg-start justify-content-center mb-lg-0 mb-3">');
document.write('                        <li><a href="javascript:void(0)">Terms</a></li>');
document.write('                        <li><a href="javascript:void(0)">Privacy</a></li>');
document.write('                        <li><a href="javascript:void(0)">Security</a></li>');
document.write('                    </div>');
document.write('                </div>');
document.write('                <div class="col-lg-4 text-center mb-3 mb-sm-0">');
document.write('                    <p class="mb-0">© 2023 W.AGENCY | All Rights Reserved</p>');
document.write('                </div>');
document.write('                <div class="col-lg-4">');
document.write('                    <div class="d-flex gap-4 justify-content-lg-start justify-content-center mb-lg-0 mb-3">');
document.write('                        <a href="javascript:void(0)"><img src="./frontend/img/socail-media/twitter.svg" alt=""></a>');
document.write('                        <a href="javascript:void(0)"><img src="./frontend/img/socail-media/Instagram.svg" alt=""></a>');
document.write('                        <a href="javascript:void(0)"><img src="./frontend/img/socail-media/facebook.svg" alt=""></a>');
document.write('                        <a href="javascript:void(0)"><img src="./frontend/img/socail-media/linkedin.svg" alt=""></a>');
document.write('                        <a href="javascript:void(0)"><img src="./frontend/img/socail-media/Instagram.svg" alt=""></a>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('        </div>');
document.write('    </div>');
document.write('</footer>');
document.write('<a class="bg_secondary" href="#" id="scroll" style="display: none;">');
document.write('    <img src="./frontend/img/apporch/arrow-up.svg" alt="">');
document.write('</a>');
