document.write('<nav class="navbar fixed-top">');
document.write('    <div class="container">');
document.write('        <a class="navbar-brand theme_logo" href="./index.html">');
document.write('                <h2 class="brand-name"><span>W. </span><span class="agency">AGENCY</span></h2>');
document.write('        </a>');
document.write('        <div class="toggle_wrap">');
document.write('            <a href="./register.html" class="theme_btn theme_btn_outline">Register</a>');
document.write('            <button class="navbar-toggler p-0 border-0" type="button" data-bs-toggle="offcanvas"');
document.write('                data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">');
document.write('                <span class="navbar-toggler-icon"></span>');
document.write('            </button>');
document.write('        </div>');
document.write('        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"');
document.write('            aria-labelledby="offcanvasNavbarLabel">');
document.write('            <div class="offcanvas-header">');
document.write('                <a href="" class="theme_logo navbar-brand">');
document.write('                       <h2 class="brand-name"><span>W. </span><span class="agency">AGENCY</span></h2>');
document.write('                </a>');
document.write('                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>');
document.write('            </div>');
document.write('            <div class="offcanvas-body">');
document.write('                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./index.html" class="nav-link active" aria-current="page">Home</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./about.html" class="nav-link">About Us</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./services.html" class="nav-link">Services</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./our-business-goal.html" class="nav-link">Our Goal</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./blog.html" class="nav-link">Blogs</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./career.html" class="nav-link">Careers</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./price.html" class="nav-link">Pricing</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./our-approach.html" class="nav-link">Our Approach</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./contact-us.html" class="nav-link">Contact Us</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item Register">');
document.write('                        <a href="./register.html" class="nav-link">Register</a>');
document.write('                    </li>');
document.write('                </ul>');
document.write('            </div>');
document.write('        </div>');
document.write('    </div>');
document.write('</nav>');
