document.write('<nav class="navbar fixed-top">');
document.write('    <div class="container">');
document.write('        <a class="navbar-brand theme_logo" href="./index.html">');
document.write('            <img src="./frontend/img/home-page/Gro.Pro.svg" id="logo-light" class="obj_fit_contain" alt="Gro.Pro">');
document.write('        </a>');
document.write('        <div class="toggle_wrap">');
document.write('            <a href="javascript:void(0)" class="theme_btn theme_btn_outline">Register</a>');
document.write('            <button class="navbar-toggler p-0" type="button" data-bs-toggle="offcanvas"');
document.write('                data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">');
document.write('                <span class="navbar-toggler-icon"></span>');
document.write('            </button>');
document.write('        </div>');
document.write('        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"');
document.write('            aria-labelledby="offcanvasNavbarLabel">');
document.write('            <div class="offcanvas-header">');
document.write('                <a href="" class="theme_logo">');
document.write('                    <img src="./frontend/img/home-page/Gro.Pro.svg" class="obj_fit_contain" alt="Gro.Pro">');
document.write('                </a>');
document.write('                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>');
document.write('            </div>');
document.write('            <div class="offcanvas-body">');
document.write('                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./index.html" class="nav-link active" aria-current="page" href="#">Home</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./about.html" class="nav-link" href="#">About Us</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./services.html" class="nav-link" href="#">Services</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./our-business-goal.html" class="nav-link" href="#">Our Goal</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./blog.html" class="nav-link" href="#">Blogs</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./carrare.html" class="nav-link" href="#">Careers</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./price.html" class="nav-link" href="#">Pricing</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./our-approach.html" class="nav-link" href="#">Our Approach</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item">');
document.write('                        <a href="./contact-us.html" class="nav-link" href="#">Contact Us</a>');
document.write('                    </li>');
document.write('                    <li class="nav-item Register">');
document.write('                        <a href="javascript:void(0)" class="nav-link" href="#">Register</a>');
document.write('                    </li>');
document.write('                </ul>');
document.write('            </div>');
document.write('        </div>');
document.write('    </div>');
document.write('</nav>');
